# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_img_names": "00_utils.ipynb",
         "check_lists_identical": "00_utils.ipynb",
         "img_path_to_xarr": "00_utils.ipynb",
         "last2dims": "00_utils.ipynb",
         "check_channels_input_suitable_and_return_channels": "00_utils.ipynb",
         "extend_region_properties_list": "00_utils.ipynb",
         "add_scale_regionprops_table_area_measurements": "00_utils.ipynb",
         "lazy_props": "00_utils.ipynb",
         "reorder_df_to_put_ch_info_first": "00_utils.ipynb",
         "is_label_image": "00_utils.ipynb",
         "generate_random_cmap": "00_utils.ipynb",
         "what_cmap": "00_utils.ipynb",
         "figure_rows_columns": "00_utils.ipynb",
         "auto_figure_size": "00_utils.ipynb",
         "crop_RGB_img_to_square": "00_utils.ipynb",
         "plot_new_images": "00_utils.ipynb",
         "RGB_image_from_CYX_img": "00_utils.ipynb",
         "four_ch_CYX_img_to_three_ch_CYX_img": "00_utils.ipynb",
         "plot_threshold_imgs_side_by_side": "00_utils.ipynb",
         "region_overlap": "00_utils.ipynb",
         "calculate_overlap": "00_utils.ipynb",
         "calc_allfilt_from_thresholds": "00_utils.ipynb",
         "concat_list_of_thresholds_to_string": "00_utils.ipynb",
         "generate_touch_counting_image": "00_utils.ipynb",
         "adjusted_cell_touch_images": "00_utils.ipynb",
         "calc_neighbours": "00_utils.ipynb",
         "get_all_labeled_clones_unmerged_and_merged": "00_utils.ipynb",
         "determine_labels_across_other_images_using_centroids": "00_utils.ipynb",
         "calculate_corresponding_labels": "00_utils.ipynb",
         "update_1st_coord_and_dim_of_xarr": "00_utils.ipynb",
         "CloneCounter": "01_clone_counters.ipynb",
         "LazyCloneCounter": "01_clone_counters.ipynb",
         "PersistentCloneCounter": "01_clone_counters.ipynb",
         "query_df_groupby_by_clone_channel": "02_clone_analysis.ipynb",
         "create_stack_bar_plot": "02_clone_analysis.ipynb",
         "plot_stat_annotation": "02_clone_analysis.ipynb",
         "pvals_to_stat_anots": "02_clone_analysis.ipynb"}

modules = ["utils.py",
           "clone_counters.py",
           "clone_analysis.py"]

doc_url = "https://morriso1.github.io/clonedetective/"

git_url = "https://github.com/morriso1/clonedetective/tree/master/"

def custom_doc_links(name): return None
