# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_img_names": "00_utils.ipynb",
         "check_lists_identical": "00_utils.ipynb",
         "img_path_to_xarr": "00_utils.ipynb",
         "last2dims": "00_utils.ipynb",
         "extend_region_properties_list": "00_utils.ipynb",
         "add_scale_regionprops_table_area_measurements": "00_utils.ipynb",
         "lazy_props": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://morriso1.github.io/py_clone_detective/"

git_url = "https://github.com/morriso1/py_clone_detective/tree/{branch}/"

def custom_doc_links(name): return None
