# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_img_names": "00_utils.ipynb",
         "check_lists_identical": "00_utils.ipynb",
         "img_path_to_xarr": "00_utils.ipynb",
         "last2dims": "00_utils.ipynb",
         "check_channels_input_suitable_and_return_channels": "00_utils.ipynb",
         "extend_region_properties_list": "00_utils.ipynb",
         "add_scale_regionprops_table_area_measurements": "00_utils.ipynb",
         "lazy_props": "00_utils.ipynb",
         "reorder_df_to_put_ch_info_first": "00_utils.ipynb",
         "region_overlap": "00_utils.ipynb",
         "calculate_overlap": "00_utils.ipynb",
         "generate_touch_counting_image": "00_utils.ipynb",
         "label_clones_output_unmerged_and_merged": "00_utils.ipynb",
         "get_all_labeled_clones_unmerged_and_merged": "00_utils.ipynb",
         "update_1st_coord_and_dim_of_xarr": "00_utils.ipynb",
         "CloneCounter": "01_clone_counters.ipynb",
         "LazyCloneCounter": "01_clone_counters.ipynb",
         "PersistentCloneCounter": "01_clone_counters.ipynb",
         "combine_agg_functions": "02_clone_analysis.ipynb",
         "individual_filter_condition": "02_clone_analysis.ipynb",
         "query_df_groupby_by_clone_channel": "02_clone_analysis.ipynb"}

modules = ["utils.py",
           "clone_counters.py",
           "clone_analysis.py"]

doc_url = "https://morriso1.github.io/py_clone_detective/"

git_url = "https://github.com/morriso1/py_clone_detective/tree/master/"

def custom_doc_links(name): return None
